package Design;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.geom.RoundRectangle2D;
import javax.swing.Timer;
import rojerusan.RSAnimation;

public class Splash extends javax.swing.JFrame {
    
    private Timer t;
    private int n = 0;

    public Splash() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.repaint();
        this.setBackground(new Color(0, 0, 0, 180));
        this.addComponentListener(new ComponentAdapter() { 
            @Override
            public void componentResized(ComponentEvent e) {
                setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
            }
        });
        
        Progress.setValue(0);
        Progress.setColorBackground(new Color(0,0,0,0));
                
        RSAnimation.setMoverDerecha(-400, 10, 1, 1, JLabelLogo);
        RSAnimation.setBajar(-380, 28, 2, 1, pnlTexto);
        RSAnimation.setMoverIzquierda(800, 400, 2, 1, jLabelLoad);
        
        ActionListener accion = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (n <= 100) {
                    Progress.setValue(n);
                    n = n+5;
                }else {
                    t.stop();
                    dispose();
                    new Design.Register().setVisible(true);
                }

            }
        };
        t = new Timer(300, accion);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSProgressBarSinTextBeanInfo1 = new rojerusan.componentes.RSProgressBarSinTextBeanInfo();
        fSGradientPanel1 = new LIB.FSGradientPanel();
        JLabelLogo = new javax.swing.JLabel();
        jLabelLoad = new rojeru_san.rslabel.RSLabelBorderRound();
        Progress = new rojerusan.componentes.RSProgressBarSinText();
        pnlTexto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fSGradientPanel1.setFSEndColor(new java.awt.Color(73, 90, 255));
        fSGradientPanel1.setFSStartColor(new java.awt.Color(10, 207, 254));
        fSGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/calendario.png"))); // NOI18N
        fSGradientPanel1.add(JLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 200, -1));

        jLabelLoad.setForeground(new java.awt.Color(255, 255, 204));
        jLabelLoad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLoad.setText("Cargando...");
        jLabelLoad.setBgBorde(new java.awt.Color(66, 82, 246));
        jLabelLoad.setFont(new java.awt.Font("Fredoka One", 1, 18)); // NOI18N
        fSGradientPanel1.add(jLabelLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 140, -1));

        Progress.setForeground(new java.awt.Color(102, 153, 255));
        Progress.setBorderPainted(false);
        Progress.setColorForeground(new java.awt.Color(102, 102, 255));
        Progress.setGrosorBorde(0);
        Progress.setOpaque(false);
        fSGradientPanel1.add(Progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 550, 20));

        pnlTexto.setOpaque(false);
        pnlTexto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("bubbleboddy", 0, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Caloric");
        pnlTexto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("bubbleboddy", 0, 62)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Routine");
        pnlTexto.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        fSGradientPanel1.add(pnlTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 28, 330, 170));

        getContentPane().add(fSGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelLogo;
    private rojerusan.componentes.RSProgressBarSinText Progress;
    private LIB.FSGradientPanel fSGradientPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private rojeru_san.rslabel.RSLabelBorderRound jLabelLoad;
    private javax.swing.JPanel pnlTexto;
    private rojerusan.componentes.RSProgressBarSinTextBeanInfo rSProgressBarSinTextBeanInfo1;
    // End of variables declaration//GEN-END:variables
}
